package cmd

import (
	"errors"
	"fmt"
	"os"

	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
)

// defaultConfig is written by `smelt config init`.
// Kept in sync with config.yaml.example at the repo root.
const defaultConfig = `# smelt configuration
# Generated by ` + "`smelt config init`" + `. Copy to config.yaml or pass --config <path>.
# All values can be overridden with CLI flags or SMELT_* environment variables.
# Precedence: CLI flag > env var > config.yaml > built-in default.

smelt:
  # Maximum simultaneous ffmpeg processes. 0 = runtime.NumCPU().
  workers: 0

  # Log verbosity: debug | info | warn | error
  log_level: info

  # Log format: auto | json | pretty
  # auto selects pretty when stdout is a TTY, json otherwise.
  log_format: auto

transcode:
  # Root directory to scan recursively for media files.
  src: ""

  # File extensions to match (case-insensitive, leading dot optional).
  ext:
    - mkv
    - mp4
    - avi

  # Encode settings. Left commented so a --profile drives them; uncomment to
  # pin a value (a value set here outranks any --profile, per the precedence
  # below). Shown values are the built-in defaults.
  #
  # codec: h265     # target video codec: h264 | h265 | av1 | vp9
  # crf: 23         # constant rate factor 0-51; lower = higher quality
  # preset: medium  # ultrafast | fast | medium | slow | veryslow

  # Replace original file after a confirmed successful transcode.
  # WARNING: the original is unrecoverable after this operation.
  inplace: false

  # Write output files to this directory instead of alongside the source.
  # The directory must exist. Mutually exclusive with inplace: true.
  output_dir: ""

  # Temporary filename suffix applied during an active transcode.
  # Removed on success; triggers cleanup on failure.
  suffix: ".smelt"

# Named profiles — apply with: smelt transcode --profile <name>
# Built-in profiles (web, web-hevc, archive, av1, mobile) ship in the binary and
# need no config. Run ` + "`smelt profiles`" + ` to list them and
# ` + "`smelt profiles show <name>`" + ` to see the exact flags each expands to. A
# profile below of the same name overrides the built-in field-by-field; a new
# name adds a profile. Every key mirrors a transcode.* flag: codec, crf, preset,
# audio_codec, audio_bitrate, to, subs, extra_args.
profiles:
  # Customise the built-in web profile: keep its audio/container/faststart,
  # just raise the quality (lower crf).
  web:
    crf: 20

  # A profile of your own.
  hevc-1080p:
    codec: h265
    crf: 22
    preset: slow
    audio_codec: aac
    audio_bitrate: 160k
    to: mkv
    extra_args:
      - "-vf"
      - "scale=-2:1080"
`

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Manage smelt configuration",
	Long:  "Manage smelt configuration.",
}

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Write a default config.yaml to the current directory",
	Long: `Write a default config.yaml to the current working directory.
Fails if config.yaml already exists; use --force to overwrite.`,
	RunE: runConfigInit,
}

func init() {
	configInitCmd.Flags().Bool("force", false, "overwrite an existing config.yaml")
	configCmd.AddCommand(configInitCmd)
	rootCmd.AddCommand(configCmd)
}

func runConfigInit(cmd *cobra.Command, args []string) error {
	force, _ := cmd.Flags().GetBool("force")
	const target = "config.yaml"

	if !force {
		if _, err := os.Stat(target); err == nil {
			return fmt.Errorf("%s already exists; use --force to overwrite", target)
		} else if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("stat %s: %w", target, err)
		}
	}

	if err := os.WriteFile(target, []byte(defaultConfig), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", target, err)
	}

	log.Info().Str("path", target).Msg("config written")
	fmt.Printf("wrote %s\n", target)
	return nil
}
